import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SecondaryNavBar from "@/components/secondaryNavBar";
import { MainNavBar } from "@/components/MainNavBar";
// import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
          <SecondaryNavBar/>
          <div className="bg-gradient-to-br from-indigo-100 to-white h-hero">
            <MainNavBar/>
            {children}
          </div>
        {/* </ThemeProvider> */}
      </body>
      
    </html>
  );
}
